language: c

compiler: gcc-8

instal:
  - gcov

script:
  - cd ./bonus/automated_test
  - chmod +x *.sh
  - ./install_criterion.sh
  - cd ../../
  - make tests_compile
  - ./42sh_tester -j1 --always-succeed
  - gcov *
