language: c

compiler: gcc-8

sudo: required

instal:
  - gcov

notifications:
  email:
    recipients:
    - florent.poinsard@epitech.eu
    - julien.ollivier@epitech.eu
    - cecile.cadoule@epitech.eu
    - florian.davasse@epitech.eu
    on_success: always
    on_failure: always

script:
  - cd ./bonus/automated_test
  - chmod +x *.sh
  - ./install_criterion.sh
  - cd ../../
  - make tests_compile
  - ./42sh_test -j1 --always-succeed
  - gcov *
